### ISSUE TITLE
Unable to run command python3 client.py

### ISSUE THREAD

**Issue by abdulsami786** [IAMIQBAL/Voice-Controlled-Shell#1]
@IAMIQBAL

when where I am running python3 client.py in ubuntu 18.04 terminal  I am getting an error line 1 in <module> 
import zmq
modulenotfounderror: No module named 'zmq' 
![Screenshot 2022-03-16 042411](https://user-images.githubusercontent.com/76508402/158488278-843c3682-2ccb-430a-b97d-6bbcd39b86d3.png)
  please help me out.

**Comment by IAMIQBAL** [comment]
You need to install zmq library.
See if `pip3 install zmq` works

**Comment by abdulsami786** [comment]
@IAMIQBAL Thanks for your reply and time, now I am getting this error, can you please take moment to see how to resolve this
![Screenshot 2022-03-16 051900](https://user-images.githubusercontent.com/76508402/158492873-dae63be9-a0fe-4303-b276-dde526a95f33.png)

**Comment by IAMIQBAL** [comment]
Make sure you are connected to the internet and has a mic connected that takes speech (input)

**Comment by abdulsami786** [comment]
I am connected with internet and microphone but stuck with the same error/ problem, can you please arrange a google meet/ zoom slot to help me out.
Thanks.

**Comment by abdulsami786** [comment]
![Screenshot 2022-03-17 035514](https://user-images.githubusercontent.com/76508402/158704640-2238cc29-f376-44ab-81e2-cd00060e9235.png)

You can see I have tested microphone and internet and it is working fine but when I am running python3 client.py it is giving error.

**Comment by abdulsami786** [comment]
Yes, I am connected with Internet and microphone, can you please arrange me
time slot and guide me on meet or zoom.
I will be very thankful to you.
Thanks.
